
GET http://localhost:5001/booking HTTP/1.1
###
POST http://localhost:5001/booking/admin HTTP/1.1
content-type: application/json

{
    "name": "name",
    "phone": "phone",
    "email": "email",
    "booking": "booking",
    "bookingDate": "booking date",
    "message": "message"
}